### ISSUE TITLE
Should depth 0 be a h1 or p instead of h0?

### ISSUE THREAD

**Issue by d4rekanguok** [mrzmmr/remark-behead#4]
Hi, great plugin!

I notice that with option `{ depth: 1 }`, my `h6` stays `h6`; but with setting `{ depth: -1 }`, my `h1` becomes `h0`.

I think logically `h1` should stay `h1`, or become a different tag like `p` instead?

**Comment by mrzmmr** [comment]
Hey thanks, your right `h1` should stay `h1`. It wouldn't be difficult to have `h0` become a `p` but I think staying an `h1` should be the default behavior.
