### ISSUE TITLE
TypeScript compatibility

### ISSUE THREAD

**Issue by pacocom** [mrzmmr/remark-behead#6]
`import behead from 'remark-behead';`

Could not find a declaration file for module 'remark-behead'. 'c:/Users/Francisco/Documents/baikal-global/developers/node_modules/remark-behead/index.js' implicitly has an 'any' type.
  Try `npm install @types/remark-behead` if it exists or add a new declaration (.d.ts) file containing `declare module 'remark-behead';`

**Comment by crutchcorn** [comment]
I am able to write these TypeScript definitions, but I would like to wait until this PR is merged:

#15

Since it'll impact how TS files are written
